initial dev
Stretch-com/stretch-client-sample-application pull request #1
Opened 2024-04-24 07:02 UTC by Nir0n

2024-04-24 11:48 UTC, stretchcom requested changes

2024-04-24 11:48 UTC, stretchcom commented on category.py
> +    return session.get("/categories")
base_url ?

2024-04-24 11:48 UTC, stretchcom commented on client.py
> +    res = session.post(f"{base_url}/client", data=json.dumps(dto_in.dict()))
We can use  json=dto_in.dict().  instead convertion

2024-04-24 11:48 UTC, stretchcom commented on search.py
> +base_url = os.getenv('STRETCH_PUBLIC_API_URL', 'http://localhost:8000/api/v1/public')
default value better setup on api.stretch.com

2024-04-24 11:48 UTC, stretchcom commented on search.py
> +    return  session.post("/search", data=json.dumps(dto_in.dict(), cls=JSONEncoder))
We return json ?

2024-04-26 11:03 UTC, Nir0n commented on search.py
> +    return  session.post("/search", data=json.dumps(dto_in.dict(), cls=JSONEncoder))
yes

2024-04-29 07:25 UTC, stretchcom approved these changes

2024-04-29 07:25 UTC, merged